### ISSUE TITLE
Disabling ringtone does not disable the ringtone

### ISSUE THREAD

**Issue by tjw0051** [amazon-connect/amazon-connect-streams#284] opened 2020-07-20 12:57 UTC
Following the docs for disabling ringtone is not working, the ringtone still plays:
```javascript
connect.core.initCCP(containerDiv, {
          ccpUrl: instanceURL,            // REQUIRED
          loginPopup: true,               // optional, defaults to `true`
          region: "eu-central-1",         // REQUIRED for `CHAT`, optional otherwise
          softphone: {                    // optional
               allowFramedSoftphone: true,   // optional
               disableRingtone: true,       // optional
           },
          chat: {
              disableRingtone: true
          }
});
```
Adding a custom ringtone does not change the default either. Am I missing something in the config here?

**Comment by jolim24601** [comment] 2020-07-20 19:27
Hi @tjw0051 is this the case for both softphone and chat?

**Comment by jolim24601** [comment] 2020-07-20 20:24
We are aware there is an issue with chat params to `initCCP` in the latest release. The issue is not with Streams but with the embedded CCP. We are working on resolving the issue and will update here when it is fixed.

**Comment by tjw0051** [comment] 2020-07-21 10:32
@jolim24601 Yes with both softphone and chat.

Thanks for the update.

**Comment by sseidel16** [comment] 2020-07-21 23:21
@tjw0051 custom ringtones should work in softphone. I only have issues with chat custom ringtones. Maybe there is some other issue happening with your softphone

**Comment by jolim24601** [comment] 2020-08-03 18:03
Hi @sseidel16 and @tjw0051 this issue should be fixed now.

**Closed by jolim24601** 2020-08-03 18:03 UTC
Labels: bug

**Comment by sseidel16** [comment] 2020-08-04 00:57
I can confirm it's working now.

**Comment by steadweb** [comment] 2020-12-08 19:05
@sseidel16 what version was this fixed in?

**Comment by manojverma086** [comment] 2024-02-21 08:10
We are looking for disabling ringtone for task, how can we do it?
