### ISSUE TITLE
Microphone does not work in Firefox when I popup the CCP in a separate window

### ISSUE THREAD

**Issue by marcogrcr** [amazon-connect/amazon-connect-streams#271] opened 2020-06-18 21:24 UTC
We have a use case that shows the built-in CCP inside our application and allows customers to "pop-out" the CCP into a separate window, as well as "pop-back" the CCP.

Receiving calls from the popup using the softphone works just fine in `Chrome`, however when I use `Firefox ESR`, clicking the accept call button doesn't work. According to the [official documention](https://docs.aws.amazon.com/connect/latest/adminguide/browsers.html), `Firefox ESR` is supported.

A simplified version looks like this:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>microphone test</title>
    <script src="/node_modules/amazon-connect-streams/release/connect-streams.js"></script>
  </head>
  <body>
    <button id="pop-out">Pop out!</button>
    <button id="pop-in">Pop in!</button>
    <div id="ccp-container"></div>
    <script>
      const CCP_URL = "https://my-instance.awsapps.com/connect/ccp-v2";
      const LOGIN_URL = "https://my-login-url/";
      const CONTAINER = document.getElementById("ccp-container");
      let popup;

      document.getElementById("pop-out").addEventListener("click", () => {
        popup = window.open(
          CCP_URL,
          "CCP",
          "height=500,width=320,menubar=0,status=0,toolbar=0"
        );

        CONTAINER.style.display = "none";
      });

      document.getElementById("pop-in").addEventListener("click", () => {
        popup.close();

        CONTAINER.style.display = "";
      });

      connect.core.initCCP(CONTAINER, {
        ccpUrl: CCP_URL,
        region: "us-east-1",
        loginUrl: LOGIN_URL,
        loginPopup: true,
        loginPopupAutoClose: true,
        softphone: {
          allowFramedSoftphone: true,
        },
      });
    </script>
  </body>
</html>
```

---

**Environment:**

- **OS:** `MacOS 10.14.6`
- **Browsers:** `Chrome 83.0.4103.97` / `Firefox ESR 68.8.0esr`
- **amazon-connect-streams:** `1.4.8`

**Comment by marcogrcr** [comment] 2020-06-18 21:36
# Steps to reproduce:

1. Load the example html on an https origin that is whitelisted in Amazon Connect. Wait for the CCP to load and the prompt for microphone permissions to show, click the "Allow" button.

![initial-load](https://user-images.githubusercontent.com/1108126/85073632-f9e14e00-b16f-11ea-8ed0-c19d1063ff0f.png)

2. Verify that the microphone show up on the URL bar:

![url-bar](https://user-images.githubusercontent.com/1108126/85073815-517fb980-b170-11ea-8124-cb644d78ce64.png)

3. Click the "Pop out!" button, wait for the popup to open an load:

![pop-up-loaded](https://user-images.githubusercontent.com/1108126/85073867-6eb48800-b170-11ea-9907-afa393420d02.png)

4. On the popup, set yourself as "Available" and perform a phone call that would result in the call being routed to the agent:

![set-as-available](https://user-images.githubusercontent.com/1108126/85073967-9d326300-b170-11ea-8d47-c2edc7aaffbf.png)

5. When the call comes in, click the "Accept call" button:

![accept-call-button](https://user-images.githubusercontent.com/1108126/85073984-a6bbcb00-b170-11ea-99e3-a2aee9b02e22.png)

# Expected result

The call is connected and you can talk with the customer.

# Actual result

Clicking the button one or multiple times "does nothing", and after a while (i.e. a timeout), you get a microphone permissions error:

![microphone-permissions-error](https://user-images.githubusercontent.com/1108126/85074088-d7036980-b170-11ea-95c9-eb13a365ec1b.png)

Waiting a bit more (i.e. another timeout), results in a `WebRTC` error:

![webrtc-error](https://user-images.githubusercontent.com/1108126/85074187-0023fa00-b171-11ea-9a03-a25708849168.png)

**Comment by marcogrcr** [comment] 2020-06-18 21:41
Finally, for reference, here are the permissions that I had set on the browser for both origins:

**CCP container origin:**

![ccp-container-permissions](https://user-images.githubusercontent.com/1108126/85074566-9f48f180-b171-11ea-80f6-575ab724ca6b.png)

**CCP origin:**

![ccp-permissions](https://user-images.githubusercontent.com/1108126/85074588-a5d76900-b171-11ea-81a7-3b883029d1d9.png)

---

Allowing all permissions does not solve the issue.

**Comment by ctwomblyamzn** [comment] 2020-06-26 17:20
There is an ongoing internal investigation into the root cause of this bug. We acknowledge that it exists, and we are working to fix it.

**Comment by marcogrcr** [comment] 2020-07-15 22:57
Hello, I want to add an update related to this topic:

As a workaround, for Firefox, we are embedding the CCP (i.e. `/ccp-v2`) directly on the host application (i.e. displaying the `<iframe>` instead of opening a separate window). While this "works" most of the time, under the following conditions, the experience is still a bit clunky:

**Pre-conditions:**

1. The user does not have an active Amazon Connect session (or it has expired).
1. The built-in authentication requires opening a login popup to work (i.e. it cannot be embedded inside the `<iframe>`).
1. The login URL redirects the user to the CCP v2 after a successful authentication.
1. The user's last set status is "Available".

**Action:**

Initialize and show the CCP using the following code:

```js
connect.core.initCCP(container, {
  // ...
  loginPopup: true,
  loginPopupAutoClose: true,
  softphone: {
    allowFramedSoftphone: true,
  }
});
```

The authentication popup window will open, authenticate, redirect to the CCP, wait for the CCP to load/initialize, and close.

**Expected result:**

The host application window asks for microphone permissions.

**Actual result:**

The host application window **does not ask** for microphone permissions unless the user changes their status (e.g. from "Available" to "Offline").

---

Note that this does not occur if the CCP was initialized without the need of opening an authentication popup window (i.e. the session is still active). In this case, the CCP loads and the host application window asks for microphone permissions immediately after the `<iframe>` loads.

**Comment by seiyako** [comment] 2021-04-02 19:07
This issue should be resolved with [the latest release](https://github.com/amazon-connect/amazon-connect-streams/releases/tag/1.6.5).

**Closed by seiyako** 2021-04-02 19:07 UTC
Labels: bug
