### ISSUE TITLE
contact.onAccepted(...) - Contact param is null

### ISSUE THREAD

**Issue by smearlaws** [amazon-connect/amazon-connect-streams#259] opened 2020-06-03 00:43 UTC
When implementing a simple contact.onAccepted(...) event handler, the contact param is always null.  I would think that this is a bug, but would like confirmation that the contact param should be populated with a valid contact.

**Comment by marcogrcr** [comment] 2020-06-18 17:56
This is a duplicate of #247

**Comment by ctwomblyamzn** [comment] 2020-06-26 17:57
Duplicate of #247

**Closed by ctwomblyamzn** 2020-06-26 17:57 UTC
