### ISSUE TITLE
Contact Events mixed up (onIncoming, onConnecting, onAccepted)

### ISSUE THREAD

**Issue by hfahlbusch** [amazon-connect/amazon-connect-streams#218] opened 2020-02-05 10:59 UTC
Event handlers for contacts are not working properly or the documentation is misleading.

I tried to show an agent some contact attributes when his phone starts ringing, so he can decide if he wants to take the call or reject. I assumed that "onIncoming" would be the right contact event handler, but it was never fired. 

Then I tried other handlers and "onConnecting" worked, but documentation says it shouldn't.

```
contact.onConnecting()
contact.onConnecting(function (contact) { ... });
Subscribe a method to be invoked when the contact is connecting. This works with chat and softphone contacts. This state happens after the agent has accepted a softphone call or answered if not.
```

**This state happens after the agent has accepted a softphone call or answered if not.**
The handler is called before agent is pressing accept.
Is this wrong in documentation or are the contact status mixed up?

Best regards,
Helge

**Comment by ctwomblyamzn** [comment] 2020-02-13 15:37
Hi hahlbusch. Thank you for pointing this out!

We have been aware of this discrepancy in the documentation and are working on rectifying it.

Before those changes are pushed, I can tell you that, as of now, `onConnecting()` is triggered when a new contact is detected by the Connect system, before the agent hits "Accept" EXCEPT when the incoming contact is a Queue-Callback. In that case only, the onIncoming handler is invoked. `onAccepted()` should work as intended (when the agent successfully accepts a contact) for all cases. We are looking into causing clearer behavior in the future, but for now `Documentation.md` will be updated to clarify the present situation.

**Comment by ctwomblyamzn** [comment] 2020-03-31 17:20
Update: we have pushed changes to the docs. I am resolving this issue now.

**Closed by ctwomblyamzn** 2020-03-31 17:20 UTC
