### ISSUE TITLE
npm throws error when `npm run release`

### ISSUE THREAD

**Issue by midnight480** [amazon-connect/amazon-connect-streams#389] opened 2021-03-18 11:19 UTC
Hello, Team.

I tried to build a connect-stream.js of v1.6.4 by npm on Windows10 1909.
When `npm run release`, npm throws error following:

```
>npm run release

> amazon-connect-streams@1.6.4 release C:\Projects\amazon-connect\amazon-connect-streams
> tsc && gulp

(node:9956) Warning: Accessing non-existent property 'VERSION' of module exports inside circular 
(Use `node --trace-warnings ...` to show where the warning was created)
[19:54:42] Using gulpfile C:\Projects\amazon-connect\amazon-connect-streams\gulpfile.js
[19:54:42] Starting 'default'...
[19:54:42] Starting 'script'...
    at script (C:\Projects\amazon-connect\amazon-connect-streams\node_modules\undertaker\lib\set-    at bound (domain.js:413:15)
    at runBound (domain.js:424:12)
    at asyncRunner (C:\Projects\amazon-connect\amazon-connect-streams\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
[19:54:42] 'default' errored after 13 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amazon-connect-streams@1.6.4 release: `tsc && gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amazon-connect-streams@1.6.4 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tetsuya\AppData\Roaming\npm-cache\_logs\2021-03-18T10_54_42_799Z-debug.log 

>
```

I got an answer from AWS Japan technical support team that the following variables and objects are not defined.

`.\amazon-connect-streams\gulpfile.js`
　`sourceCode`
　 `DESTINATION_FOLDER` 
`.\amazon-connect-streams\\src\event.js`
　`DisasterRecoveryEvents`

**Comment by derangedgirl** [comment] 2021-03-25 19:05
I have the same issue. Is there a fix for this one or do we need to do anything to update the gulpfile?

**Comment by eva-barton** [comment] 2021-03-31 17:29
I'm gettting the same error. Is there a fix for this issue yet?

**Comment by seiyako** [comment] 2021-04-02 19:41
Hi, this is Seiya from Connect team. I confirmed that the `npm run release` command fails because the gulp file is broken. Please try the [latest version](https://github.com/amazon-connect/amazon-connect-streams/releases/tag/1.6.5) we've just released.

**Closed** 2021-04-02 19:41 UTC

**Comment by ptegan** [comment] 2021-04-03 09:52
Latest version is confirmed to be working. Thanks for the support!

**Comment by midnight480** [comment] 2021-04-07 08:38
Thanks for fixing this issue!
