### ISSUE TITLE
Event subscriptions testing within react app

### ISSUE THREAD

**Issue by vikmn** [amazon-connect/amazon-connect-streams#336] opened 2020-11-24 15:26 UTC
Hi,
i am looking to add some tests to verify the behaviour of react components based on some of the subscriptions. Are there any examples on how i can do this? 
A simple example of this in the line below  i am interested in testing the behaviour that happens when the agent onstate change is fired
```
 useEffect(() => {
    // eslint-disable-next-line no-undef
    connect.agent((agent) => {
      agent.onStateChange(agentStateChange => 
       ///my behaviour logic 
    });
  }, []);
```

**Comment by Nicole1991** [comment] 2021-02-25 06:02
@vikmn hi, Do you have any update about this?

**Comment by SamSchiff** [comment] 2021-07-28 15:50
Hi all, the best way to test code like this is to mock out functions that facilitate your behavior logic. That way, you're guaranteeing that the code you're relying on for you test is working exactly as you expect it to, and then you can focus only on the behavior you're actually trying to test. There's multiple libraries that can mock functions, but Jest is the main one I know: https://jestjs.io/docs/mock-functions.

In this case, you'd likely want to mock both connect.agent and agent.onStateChange. If you mock the implementations to invoke a custom callback function, you can mimic the expected behavior and pass in the necessary params to test your behavior logic.

Because this is more of a question about testing with callback functions in general rather than about Streams specifically, I am going to close the issue. I hope this helps and good luck

**Closed by SamSchiff** 2021-07-28 15:50 UTC
Labels: question
