### ISSUE TITLE
Single logout in Connect

### ISSUE THREAD

**Issue by aguecida** [amazon-connect/amazon-connect-streams#165] opened 2019-11-11 15:08 UTC
I've been able to get single sign on (SSO) working between my custom app and Connect, but have not found any documentation for configuring single logout (SLO). I have configured my custom application for SLO, so that when a user clicks a logout button from my app, they are logged out from the IdP and redirected back to the sign in page. The problem is, this does not log the user out of CCP. In the agent reports, they are still in the Available state (or whatever state they were in when the user logged out from my custom app).

Does Connect support SLO? Or does the user have to logout of CCP, then logout from my custom app?

**Comment by marcogrcr** [comment] 2020-05-04 22:04
The closest thing to what you're looking for that I could find in [the documentation](https://github.com/amazon-connect/amazon-connect-streams/blob/master/cheat-sheet.md) is `https://<instance>.awsapps.com/connect/logout`

However, that may not work for you because of the following issues:

1. You cannot call it from your APP using JavaScript due to CORS.
1. Amazon Connect responds a `GET https://<instance>.awsapps.com/connect/logout` with a `302 > https://<instance>.awsapps.com/connect/login` which you don't have control over.

I couldn't find any documentation that suggested you could put a `returnUrl` argument to `/connect/logout` so that you could potentially do something like:

- `GET https://myapp.com/logout`: Performs logout of my app
  - `302 > https://<instance>.awsapps.com/connect/logout?returnUrl=https%3A%2F%2Fmyapp.com%2Flogin`
- `GET https://<instance>.awsapps.com/connect/logout?returnUrl=https%3A%2F%2Fmyapp.com%2Flogin`: Performs logout of Amazon Connect
  - `302 > https://myapp.com/login`
- `GET http://myapp.com/login`: Shows login page of my app

**Comment by jolim24601** [comment] 2020-05-21 16:55
Closing as it's a duplicate of #55

**Closed by jolim24601** 2020-05-21 16:55 UTC
Labels: enhancement
