### ISSUE TITLE
can amazon-connect-streams support logout function?

### ISSUE THREAD

**Issue by Eassson** [amazon-connect/amazon-connect-streams#55] opened 2018-05-01 09:02 UTC
I have supported Single Logon by SAML with AWS Connect,But when I want to Single Logout,I found no way to support this feature, if the streams javascript API support logout current login agent ,that would be great job! thanks!

**Comment by mschersten** [comment] 2018-12-19 21:59
+1 on this.  We have integrated with SAML, with agents logging in and out of our application, but the next user on the same computer logs in under their account and is given no indication that they are logged in as a different user on the phone.  Aside from being user-unfriendly, this requires that the CCP be present and cannot be replaced with a custom CCP.

**Comment by dustinhayes** [comment] 2019-08-02 14:29
+1 on this for the same reasoning as @mschersten

**Comment by ctwomblyamzn** [comment] 2020-09-02 18:25
This is a duplicate of #13

**Closed by ctwomblyamzn** 2020-09-02 18:25 UTC
Labels: duplicate
