### ISSUE TITLE
How to detect if a call is being monitored

### ISSUE THREAD

**Issue by andrei-at-work** [amazon-connect/amazon-connect-streams#329] opened 2020-11-13 19:40 UTC
When a manager is live monitoring a voice call, I can see a connection of type "monitoring", however connection.getMonitorInfo() always returns null. Has this been implemented? How can I determine which agent and contact is being monitored? 

When I look at the agent being monitored, I can see two connections, one of type "agent" and one of type "inbound". There is no indication that anything is being monitored. How can I determine if the call is being monitored? 

How can we match the monitoring connection to the agent connection to determine if a call is being monitored?

NOTE: It looks like getMonitorInfo() is populated during Chat monitoring connections but not Voice monitoring connections (however, the monitor info does contain enough information to determine which call is being monitored).

**Comment by andrei-at-work** [comment] 2020-11-25 16:45
Anyone care to comment?

**Comment by seiyako** [comment] 2021-05-28 14:18
Hi @andrei-at-work , sorry for the delayed response.
I can reproduce that getMonitorInfo() always returns undefined for voice connections as opposed to chat connections. I believe this is a bug as the data populated there is not specific to chat connections. We'll take this into our backlog to address the issue.
```js
// example object you get from getMonitorInfo()
{
    "agent": {
        "agentName": "xxxxxxxx"
    },
    "joinTimeStamp": "2021-05-28T14:10:48.401Z"
}
```

Speaking of the agent being monitored, there's no way to know if there's a connection that's being monitored from the agent's perspective, as of now.

**Comment by martin-greenberg** [comment] 2022-01-06 19:54
closing as duplicate of #293 and tracking there -- this is still in our backlog, but is a longer term effort as the fix for the bug is in systems owned by partner teams.

**Closed by martin-greenberg** 2022-01-06 19:54 UTC
Labels: bug, co-team
