### ISSUE TITLE
Version 2.0.0 incorrectly lists 'StreamsJS Version: STREAMS_VERSION'

### ISSUE THREAD

**Issue by altesean** [amazon-connect/amazon-connect-streams#529] opened 2022-01-22 20:19 UTC
in Version 2.0.0 in the logs, it prints 'STREAMS_VERSION' instead of the expected '2.0.0', previously displayed correctly in 1.7.5

example log:
{
  "component": "ccp",
  "level": "INFO",
  "text": "StreamsJS Version: STREAMS_VERSION",
  "time": "2022-01-22T19:13:54.029Z",
  "exception": "null",
  "objects": "[]",
  "line": 8,
  "agentResourceId": null,
  "loggerId": "1642878832848",
  "_oriKey": 12,
  "_ts": 1642878834029,
  "_key": 17
}

**Comment by martin-greenberg** [comment] 2022-01-24 21:19
Thanks for reporting, looking into this.

**Comment by martin-greenberg** [comment] 2022-04-20 21:03
Merged the PR and the issue is fixed from version 2.1.1.

**Closed by martin-greenberg** 2022-04-20 21:03 UTC
Labels: bug
