### ISSUE TITLE
clarification on incoming calls connection state/status

### ISSUE THREAD

**Issue by hausermatt** [amazon-connect/amazon-connect-streams#696] opened 2023-06-23 18:04 UTC
...or is this a bug?

for a normal incoming call, upon inspecting the incoming connection. when I call `connection.getStatus().type` returns `ConnectionStateType.CONNECTED` and `connection.isConnecting()` returns false, `connection.isConnected()` returns true BUT the call has not been answered/accepted yet. 

why would an incoming call not return `ConnectionStateType.CONNECTING`?

**Comment by vpogudina** [comment] 2023-06-26 17:15
Which connection are you running this commands on? Can you share the code snippet? Maybe you are using wrong connection to get this states on?

**Comment by hausermatt** [comment] 2023-07-10 19:28
> Which connection are you running this commands on? Can you share the code snippet? Maybe you are using wrong connection to get this states on?

this is referring to a 3rd connection on a call. let's say you have a contact with just you (agent) and caller (initial connection). when you add a third **_quick connect agent_**, the connection type immediately is connected. you can simply observe this with the ccp. add a quick connect, the status will briefly be "connecting" but then transition to "connected". I was wondering why it goes to connected before the other agent accepts the call.

**Comment by gjesse** [comment] 2023-07-13 17:29
We also see this on an incoming connection. 

As the call is incoming, and before the agent answers the call: 

here you can see that `c[1]` is the participant connection
```
c[1].getEndpoint();
Endpoint {endpointARN: null, endpointId: null, type: 'phone_number', name: null, phoneNumber: '+15123872076', …}`
```

and this shows that it's connected: 

```
c[1].getStatus();
{type: 'connected', timestamp: Thu Jul 13 2023 12:27:51 GMT-0500 (Central Daylight Time)}
```

in this scenario the agent has not answered the call yet.

**Comment by hxgnZO** [comment] 2023-07-26 15:57
There are a few different types that get confusing for me with inbound calls, and I forget which one I use most heavily- but I suspect showing 'connected' with the connection refers to your webRTC connection to the "bridge" being established- meaning they are receiving an incoming connection, but the contact has not yet accepted it- but to ring at all- there has to be *some* connection state right? At least that's how I understand it. I suspect you would need to monitor the _contact_ state rather than the _connection state_ or visa versa and it's just a matter of the two being mixed up for the specific use case. They're very similar but represent different pieces of the RTC puzzle, and important to differentiate when resolving issues. Connection issues usually boil down to RTC/network problems, or some over-eager security measures- where as having connections and getting contact issues often resides within the AWS Connect application/ecosystem or your front end page. Typically you'll get event failure type logs and such at that point. 

**ContactStateType**
An enumeration listing the different high-level states that a contact can have.

ContactStateType.INIT: Indicates the contact is being initialized.
ContactStateType.INCOMING: Indicates that the contact is incoming and is waiting for acceptance. This state is skipped for ContactType.VOICE contacts but is essential for ContactType.QUEUE_CALLBACK contacts.
ContactStateType.PENDING: Indicates the contact is pending.
ContactStateType.CONNECTING: Indicates that the contact is currently connecting. For ContactType.VOICE contacts, this is when the user will accept the incoming call. For all other types, the contact will be accepted during the ContactStateType.INCOMING state.
ContactStateType.CONNECTED: Indicates the contact is connected.
ContactStateType.MISSED: Indicates the contact timed out before the agent could accept it.
ContactStateType.ERROR: Indicates the contact is in an error state.
ContactStateType.ENDED: Indicates the contact has ended.

**ConnectionStateType**
An enumeration listing the different states that a connection can have.

ConnectionStateType.INIT: The connection has not yet been initialized.
ConnectionStateType.CONNECTING: The connection is being initialized.
ConnectionStateType.CONNECTED: The connection is connected to the contact.
ConnectionStateType.HOLD: The connection is connected but on hold.
ConnectionStateType.DISCONNECTED: The connection is no longer connected to the contact.
ConnectionStateType.SILENT_MONITOR: An enhanced listen-in manager session, this state is used instead of ContactStateType.CONNECTED for manager
ContactStateType.BARGE: A special manager session mode with full control over contact actions, this state is used instead of ContactStateType.CONNECTED for manager

**Comment by hxgnZO** [comment] 2023-07-26 16:00
> Which connection are you running this commands on? Can you share the code snippet? Maybe you are using wrong connection to get this states on?

Exactly my thought. I have confused contact state and connection state many times. Sorta wish there was some more distinct connection state as it pertains to the creation of the RTC connections and what those flows looked like. The logs get absurd, but helped me a lot to set them to the highest level and watch all the RTC stuff play out, etc. Should be events for the offer/accept etc IMO.

**Comment by gjesse** [comment] 2023-07-26 16:33
In the context of a multiparty call the contact doesn't really provide enough information. If I'm conferencing in another agent, we have no place to look for information other than the connection object. Also ConnectionState being related to WebRTC state might be true, but it doesn't really make sense, since many of the connectionstate enum values are clearly in the domain of the connection voice status (eg HOLD) obviously isn't related to the WebRTC status. I would like to be able to infer enough information about the call just based on the connection status. 

Furthermore the [documentation](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#connectionisconnected) clearly states that ConnecitonState.isConnected means that "the agent is live in a conversation through this connection". I appreciate the workaround pointers but this still feels like a bug.

**Comment by vpogudina** [comment] 2023-08-01 15:49
The customer connection for the incoming call scenario is expected to be in "connected" state, in this scenario agent's connection indicates whether the call is connected to the customer, or not.

**Comment by vpogudina** [comment] 2023-08-01 20:29
I also believe that is expected behavior for the quick connected third party to have the connected state. If you dialing a number instead of quick connect - the connection will be connecting though.

**Comment by hausermatt** [comment] 2023-09-06 16:04
> To better help you I need to understand what exactly you are trying to achieve, why do you need to catch the connecting state? If you can provide more information about your use case maybe I can suggest another solution.

we just want a way to show/describe a connection as _unanswered_ vs. accepting the call

**Closed** 2023-12-13 15:37 UTC
Labels: no-issue-activity, no-issue-activity-auto-closed
