### ISSUE TITLE
Expose agent ARN

### ISSUE THREAD

**Issue by CiscoKidxx** [amazon-connect/amazon-connect-streams#126] opened 2019-07-25 11:33 UTC
> Got it, thanks. We were planning on exposing ARN, I'll make sure that when we do so we also expose the Username.
> 
> As an aside, the cookie referenced previously ("username") looks like it's the cookie used by the signin page to pre-fill the username. I'd recommend not building any dependencies on it for two reasons: it's not managed by Amazon Connect, so I can't guarantee it'll remain consistent, and since it's for the signin page in particular it likely won't be present for federated users (either administrative federation from the AWS console, or SAML SSO federation).
> 
> _Originally posted by @ninjamike54 in https://github.com/aws/amazon-connect-streams/issues/23#issuecomment-375370864_

What is the status of exposing agent ARN ?

Use case is that UserId is needed to call certain agent based Connect API endpoints. Currently it is required to additionally listUsers to match on username to get the UserId.

**Comment by mgidea** [comment] 2019-09-24 13:41
what's the status of this issue?

**Comment by CiscoKidxx** [comment] 2019-11-12 20:41
bump

**Comment by marcogrcr** [comment] 2020-05-04 20:10
This is a duplicate of #70

**Closed** 2020-09-02 18:46 UTC
