### ISSUE TITLE
[Window IO Stream] message event came from somewhere other than the CCP iFrame streams v1.6.8

### ISSUE THREAD

**Issue by Christian-Sesta** [amazon-connect/amazon-connect-streams#436] opened 2021-06-28 03:56 UTC
Hey,
 
So I have been seeing an increasing number of these warnings since I have upgraded to version 1.6.8, which are leading to an excessive amount of logs being spat out which is messing with my teams warning/ error reporting side of things. Before the upgrade I had never seen this warning before.

Did some digging and if I understand the code that's logging this message correctly, you are making a comparison on two values which at some point can both be objects. Now since these are two objects, a simple `===`/ `==` referencial check will not work for this case as these values are not primitive values. I think you might be after `Object.is()` in this specific case, or a deep referencial check depending on if they are the exact same object references or not.

**Comment by bbolek** [comment] 2021-06-29 11:37
I am having same issue as well 
![image](https://user-images.githubusercontent.com/1146456/123790916-87a95a80-d8e7-11eb-924f-62ab50d450c9.png)

**Comment by trickyBytes** [comment] 2021-07-01 07:20
Same

**Comment by simon-fairall-vf** [comment] 2021-08-19 07:08
+1

**Comment by ctwomblyamzn** [comment] 2021-08-25 16:56
@Christian-Sesta thanks for pointing this issue out. The PR above is a WIP, but it won't fix your issue as of now. `Object.is()` is not the right solution, as that is simply a referential check as well. Can you help me understand when you face these logs? Is it perhaps possible to show me the messageEvent that causes the check to fail?

**Comment by ctwomblyamzn** [comment] 2021-11-02 19:05
@Christian-Sesta, @marktheunissen  are you embedding multiple CCPs with `initCCP` in your webapp (in a single tab)?

**Comment by ctwomblyamzn** [comment] 2021-11-02 20:40
The logic that we have in place right now relies on the fact that there is only one active iframe of CCP at a time. If there are multiple active iframes of CCP, this will cause the log spam that you have seen above. Our team is discussing how to deal with this constraint.

**Comment by marktheunissen** [comment] 2021-11-02 23:55
I don't believe we do have multiple iframes embedded. But I also can't reproduce these warnings right now which is odd. We haven't changed anything along the lines of what you're suggesting

**Comment by Christian-Sesta** [comment] 2021-11-03 00:45
@ctwomblyamzn Just had a quick look at my code, I only have one instance of the CCP iframe. Similar to @marktheunissen I dont have it occuring on one of my chrome profile sessions anymore, however, it is still occuring in my main  profile

**Comment by ctwomblyamzn** [comment] 2021-11-03 15:08
Have you both of you changed the version of streams that you were using when experiencing the issue?

**Comment by marktheunissen** [comment] 2021-11-03 22:33
Nope we are still on the same one

**Comment by Christian-Sesta** [comment] 2021-11-03 22:52
I am on v1.7.4 now and the issue still persists.

**Comment by Christian-Sesta** [comment] 2021-12-13 05:28
Curious if there has been any traction on this ticket @ctwomblyamzn?

**Comment by ctwomblyamzn** [comment] 2021-12-15 15:52
@Christian-Sesta as far as we have seen, there are no times when this log appears without there actually being post messages coming from some other iframe to the context in which streams is loaded into and `initCCP` is called within. That being said, if your streams-dependent-webapp intentionally (or unintentionally) receives postMessages from some other source, then this log will noisily appear. I asked if multiple CCPs was possible, as we have seen this in some implementers and this would also cause the problem. We are planning a major version release somewhat soon to more strictly enforce the already implied (but not documented) restriction of 1 embedded CCP per streams context rule. 

As to the noisy logging issue, we will look to address it soon.

**Comment by ctwomblyamzn** [comment] 2022-01-12 20:15
Hi all. We have released streams 2.0.0, which should eliminate this log, and it also restricts `initCCP` to exactly one iframe in a more strict manner. As such, I will be closing this ticket. Please let me know if you have issues with anything related to postMessages / our eventbus past version 2.0.0.

**Closed by ctwomblyamzn** 2022-01-12 20:15 UTC
