### ISSUE TITLE
URGENT - agent.setState() - Unexpected key enqueueNextState found in params

### ISSUE THREAD

**Issue by pthouard** [amazon-connect/amazon-connect-streams#525] opened 2022-01-18 10:56 UTC
Unable to change the state because of an error with the params enqueueNextState even set to false Or
default value

 type: 'UnexpectedParameter',
  message: 'Unexpected key enqueueNextState found in params',
  stack: [
    'UnexpectedParameter: Unexpected key enqueueNextState found in params',
    '    at ParamValidator.fail (https://fleetizen-taxisverts.my.connect.aws/static/connect-stream.js:6514:37)',
    '    at ParamValidator.validateStructure (https://fleetizen-taxisverts.my.connect.aws/static/connect-stream.js:6541:14)',
    '    at ParamValidator.validateMember (https://fleetizen-taxisverts.my.connect.aws/static/connect-stream.js:6552:21)',
    '    at ParamValidator.validate (https://fleetizen-taxisverts.my.connect.aws/static/connect-stream.js:6498:10)',
    '    at Request.VALIDATE_PARAMETERS (https://fleetizen-taxisverts.my.connect.aws/static/connect-stream.js:4957:42)',
    '    at Request.callListeners (https://fleetizen-taxisverts.my.connect.aws/static/connect-stream.js:8768:20)',
    '    at callNextListener (https://fleetizen-taxisverts.my.connect.aws/static/connect-stream.js:8758:12)',
    '    at Request.VALIDATE_CREDENTIALS (https://fleetizen-taxisverts.my.connect.aws/static/connect-stream.js:4911:53)',
    '    at Request.callListeners (https://fleetizen-taxisverts.my.connect.aws/static/connect-stream.js:8764:18)',
    '    at Request.emit (https://fleetizen-taxisverts.my.connect.aws/static/connect-stream.js:8740:10)'
  ]

**Comment by marktheunissen** [comment] 2022-01-18 13:49
Looks like a duplicate of: https://github.com/amazon-connect/amazon-connect-streams/issues/516

**Comment by martin-greenberg** [comment] 2022-02-14 22:08
Closing this as the customer has opened an internal ticket and the root cause was trying to use this feature in CCPv1 -- this feature is only supported in CCPv2.

**Closed by martin-greenberg** 2022-02-14 22:08 UTC
