### ISSUE TITLE
Login Pop up Loop if you log out from the CCP

### ISSUE THREAD

**Issue by leonelRamirez-cmyk** [amazon-connect/amazon-connect-streams#468] opened 2021-09-23 20:00 UTC
the  login pop up loops when you close session on the CCP, continues to repeat this message until login site times out for multiple request. began at 1.6.10, 1.6.9 on logout doesnt invoke the login url again. this is useing SAML

this is the console message that repeats:

ACK_TIMEOUT occurred, attempting to pop the login page if not already open

![image](https://user-images.githubusercontent.com/77397658/134575453-6b4e241f-1371-4dfc-a2ff-7983973be28a.png)

**Comment by marktheunissen** [comment] 2021-09-28 00:51
Yes we're encountering this too

**Comment by Christian-Sesta** [comment] 2021-09-29 23:25
Seen this too

**Comment by EricL0wry** [comment] 2021-12-08 22:11
We're experiencing this as well

**Comment by vpogudina** [comment] 2022-01-12 20:24
Closing this issue as a duplicate of that one https://github.com/amazon-connect/amazon-connect-streams/issues/490

**Closed by vpogudina** 2022-01-12 20:24 UTC
Labels: bug, duplicate
