### ISSUE TITLE
Not Working Amazon Connect Streams in Chrome 94 (Need to change sdpSemantics Plan)

### ISSUE THREAD

**Issue by TAKUYA-KUSAKABE** [amazon-connect/amazon-connect-streams#446] opened 2021-08-04 07:47 UTC
I tried amazon connect streams or amazon connect CCP in Chrome 94 Canary.
When I call to other user, this error occured.

Browser Logs:
```browser
Uncaught (in promise) DOMException: 
Failed to construct 'RTCPeerConnection': Plan B SDP semantics is a legacy version of the Session Description Protocol that has severe compatibility issues on modern browsers and is no longer supported.
See https://www.chromestatus.com/feature/5823036655665152 for more details, including the possibility of registering for a Deprecation Trial in order to extend the Plan B deprecation deadline for a limited amount of time.
```

I refer to below site, I knew need to modify sdpSemantics plan to using amazon connect in Chrome 94.
Could you please modify **sdpSemantics plan**?
cf. https://www.chromestatus.com/feature/5823036655665152

![スクリーンショット 2021-08-04 16 40 07](https://user-images.githubusercontent.com/54176946/128141758-8f20c80c-0ae2-4b28-9cfd-fb285b29e0e4.png)

**Comment by marktheunissen** [comment] 2021-08-04 23:42
See: https://github.com/amazon-connect/amazon-connect-streams/issues/426 and I believe the origin of the message is: https://github.com/aws/connect-rtc-js/issues/66

**Comment by ctwomblyamzn** [comment] 2021-08-06 15:20
This is a duplicate of https://github.com/amazon-connect/amazon-connect-streams/issues/426

**Closed by ctwomblyamzn** 2021-08-06 15:20 UTC
Labels: duplicate
