### ISSUE TITLE
No contact info when monitoring a voice call

### ISSUE THREAD

**Issue by tjw0051** [amazon-connect/amazon-connect-streams#293] opened 2020-08-12 15:06 UTC
When monitoring a voice call, no contact info is given, `getMonitorInfo()` returns undefined, and the contact has no name or attributes.

Additionally the `contactId` of the monitored call does not match the contactId of the contact who is connected to the agent, so we can't do any backend joining of the contactIds to fetch the contacts information.

Is this a bug? Chat contacts work fine so I wasn't sure if this is unimplemented or a deliberate decision.

**Comment by seiyako** [comment] 2021-04-30 00:44
Hi, sorry for the delayed response. Yes, I can reproduce this and I believe this is a bug. Marked as a bug to track this issue.

**Comment by vpogudina** [comment] 2021-07-28 15:21
Hi, sorry for the long response, the issue is still being tracked.

**Comment by Ra100NZ** [comment] 2022-04-08 12:23
open almost for 2 years, is the issue still being tracked? :) Any target date?

**Comment by seiyako** [comment] 2023-03-17 14:03
Hi, apologies for the delayed response. We discussed this behavior with other internal teams and the answer is that the current behavior is by design. Originally monitoringInfo field is populated to differentiate the agent names when manager is monitoring multiple agents, but since manager can only monitor one voice contact we don't need such identifier. If you would like to submit a feature enhancement request, please do so via your TAM. Thank you

**Closed by seiyako** 2023-03-17 14:03 UTC
Labels: enhancement, co-team
