### ISSUE TITLE
contact control panel integration in application. Error in connect-streams.js: Cannot set property 2011-06-15 of [object Object]

### ISSUE THREAD

**Issue by Ibrahimkhattana123** [amazon-connect/amazon-connect-streams#328] opened 2020-11-13 06:27 UTC
i am using this guide for integrating contact control panel https://github.com/CrisisCleanup/amazon-connect-streams/blob/HEAD/Documentation.md 
i have installed amazon-connect-streams using NPM package "npm install amazon-connect-streams" and by following guide embed it in the component import 'amazon-connect-streams'
and calling the function on component 
oninit(){
  let el: HTMLElement = document.getElementById('containerDiv');
    connect.core.initCCP(el, { ccpUrl: "https://oblab2.awsapps.com/connect/ccp# ",
    loginPopup: true,
      softphone: {
        allowFramedSoftphone: true
      }
  });;
}
containerDiv is added in the html. <div id=containerDiv style="width: 400px;height: 800px;"></div>

when I run this I am getting this error:

Uncaught TypeError: Cannot set property 2011-06-15 of [object Object] which has only a getter
    at Object.push../node_modules/amazon-connect-streams/release/connect-streams.js.105.../apis/connect-2017-02-15.min (connect-streams.js:21020)
    at o (connect-streams.js:4)
    at r (connect-streams.js:4)
    at Object../node_modules/amazon-connect-streams/release/connect-streams.js (connect-streams.js:4)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/ccp/ccp.component.ts (ccp.component.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/app.module.ts (app.module.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Module../src/main.ts (main.ts:1)
push../node_modules/amazon-connect-streams/release/connect-streams.js.105.../apis/connect-2017-02-15.min @ connect-streams.js:21020
o @ connect-streams.js:4
r @ connect-streams.js:4
./node_modules/amazon-connect-streams/release/connect-streams.js @ connect-streams.js:4
__webpack_require__ @ bootstrap:84
./src/app/ccp/ccp.component.ts @ ccp.component.ts:1
__webpack_require__ @ bootstrap:84
./src/app/app.module.ts @ app.module.ts:1
__webpack_require__ @ bootstrap:84
./src/main.ts @ main.ts:1
__webpack_require__ @ bootstrap:84
0 @ main.ts:12
__webpack_require__ @ bootstrap:84
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1

please guide me regarding this issue.

**Comment by theisjabra** [comment] 2020-12-11 11:21
I got this error as well. It fails on line 21051: `AWS.apiLoader.services['sts']['2011-06-15'] = require('../apis/sts-2011-06-15.min');` 

The error only happens if the library is loaded after being compiled by a module bundler (I use Rollup) or if loaded directly in the browser as an es-module. 

Minimal steps to reproduce:

index.html:
```html
<!DOCTYPE html>
<html>
<head>
  <script src="index.js" type="module"></script> 
</head>
<body>
</body>
</html>
```

index.js
```
import './node_modules/amazon-connect-streams/release/connect-streams.js';
```

Loading the library directly in a script tag works, but would like to include it in our Rollup build, so hope someone can help. 

Let me know if you need more info. Thanks.

**Comment by anantoghosh** [comment] 2021-01-23 12:50
Likely related to aws/aws-sdk-js#3555

**Comment by jgartsu12** [comment] 2021-11-21 16:10
I am getting the same error message when trying to embed the ccp in my react application.
`error - amazon-connect-streams\release\connect-streams.js (24807:3) @ Object.105.../apis/connect-2017-02-15.min
TypeError: Cannot set property 2011-06-15 of #<Object> which has only a getter
  24805 |       description: description
  24806 |     }, callbacks);
> 24807 |   };
        |   ^
  24808 | 
  24809 |   Contact.prototype.addConnection = function (endpointIn, callbacks) {
  24810 |     var client = connect.core.getClient();`

**Comment by tmokmss** [comment] 2022-06-29 11:17
The only workaround I've found so far is to use CRA instead of Vite...

**Comment by seiyako** [comment] 2023-03-03 15:34
We updated the aws sdk version in Streams v2.3.0 and since then this error should be fixed. Please reopen know if you are still seeing this issue with the recent version of Streams.

**Closed by seiyako** 2023-03-03 15:34 UTC
Labels: co-team
