### ISSUE TITLE
Can't refresh the page(window), the stream will not connect.

### ISSUE THREAD

**Issue by edward408-zhang** [amazon-connect/amazon-connect-streams#270] opened 2020-06-18 19:31 UTC
Actually, we are using react to import the stream file, and we connect the stream at the main layout, what happens is we can't avoid refresh the window, but this would cause the voice lost during the call

**Comment by ctwomblyamzn** [comment] 2020-06-19 15:35
Sorry, could you give more information? If you are referring to the warning during a refresh of streams, that is not really avoidable. What is your use-case?

**Comment by edward408-zhang** [comment] 2020-06-19 18:46
Same request about #33

**Comment by ctwomblyamzn** [comment] 2020-06-26 17:23
Unfortunately this is a long-standing bug that will probably require a long time to fix. We are aware of the issue, however. Please be aware that there are workarounds for your use case, though. If you open one CCP in a different context (not embedded) in the context that needs to be refreshed before initializing streams in the context that does need to be refreshed, by default the first CCP opened will handle all softphone media communications, meaning that refreshing the other CCP context will have no effect on the call. This is not the most convenient it could be, but it is another workaround. The other workaround I am referring to is found in the ticket you linked, https://github.com/amazon-connect/amazon-connect-streams/issues/33

**Comment by ctwomblyamzn** [comment] 2020-06-26 17:25
Duplicate of #33

**Closed by ctwomblyamzn** 2020-06-26 17:25 UTC
Labels: duplicate
